### ISSUE TITLE
 problems about using Metl on windows 

### ISSUE THREAD

**Issue by duya886** [JumpMind/metl#943]
1.
First, I want to use metl-3.5.1.r15.war on windows. I open the powershell and input "java -jar metl.war". But I cannot access the Metl User Interface by the url "http://localhost:42000/metl". In the file "logs/metl.logs", i see the following info:
2020-05-02 13:25:36,970 INFO  [PluginTransferListener] [main] Downloading: http://maven.jumpmind.com/repo/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.pom
2020-05-02 13:25:37,953 INFO  [PluginTransferListener] [main] Downloading: http://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.pom
2020-05-02 13:25:38,504 WARN  [PluginManager] [main] Failed to get class loader for org.jumpmind.metl:comp-control:3.5.1.r15
2020-05-02 13:25:38,504 WARN  [PluginManager] [main] 
java.lang.RuntimeException: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.jumpmind.metl:comp-control:jar:3.5.1.r15 -> org.jumpmind.metl:comp-abstract:jar:3.5.1.r15 -> org.jumpmind.metl:resource-core:jar:3.5.1.r15 -> org.bouncycastle:bcprov-jdk15on:jar:1.61
……
I think it is because Mtel can not download files by the url "http://repo1.maven.org/maven2", which should be "https://repo1.maven.org/maven2".

2.
Then I use metl-3.1.2.r.78.war. It works well. But I want to know if Metl can write files on a Hadoop Distributed File System (HDFS). And, can Metl read data from and write data to databases like Hbase and MongoDB which are not SQL compliant relational database？

**Comment by gwilmer** [comment]
Try version 3.6.0.  The maven repo switched from http to https.  It should be corrected in 3.6.0.

There are currently no out of the box resources or components for MongoDB or Hbase, but Metl is setup in such a way that different resources and component can be easily added.  Here's a blog article on creating custom components which may help.

https://www.jumpmind.com/blog/creating-custom-metl-components-2

**Comment by duya886** [comment]
Thank you. I still have a problem. Cound Metl write files on a Hadoop Distributed File System (HDFS) by File Reader/Writers?
